# Generated by Django 4.0.4 on 2022-07-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of this repo', max_length=250)),
                ('link', models.URLField(help_text='A link to the Github repo')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('log_file', models.FileField(help_text='The pytest HTML log file', upload_to='base/')),
                ('test_file', models.URLField(help_text='A link to the actual test cases.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.repo')),
            ],
            options={
                'unique_together': {('repo', 'slug')},
            },
        ),
    ]
