# Generated by Django 4.0.4 on 2022-07-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_entry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, help_text='A description to display on the page', max_length=200),
        ),
    ]
