# Generated by Django 4.0.4 on 2022-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_entry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reference_link',
            field=models.URLField(blank=True, help_text="An optional link to what this aims to test. I.e. Pr's"),
        ),
    ]
