# Generated by Django 4.0.4 on 2022-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_entry_reference_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='log_file',
            field=models.FileField(help_text='The pytest HTML log file', upload_to='nexttest/base/'),
        ),
    ]
