# Generated by Django 4.0.4 on 2022-07-18 07:58

import base.models.entry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_entry_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='log_file',
            field=models.FileField(help_text='The pytest HTML log file', upload_to=base.models.entry.get_file_path),
        ),
    ]
